// Mock events data
  const mockEvents = [
    {
      id: '1',
      title: 'Epic Music Festival 2025',
      description: 'Join thousands for the biggest music event of the year featuring top artists from around the world.',
      date: '2025-07-15T18:00:00Z',
      location: 'Central Park, NYC',
      price: 89.99,
      district: 'Manhattan',
      type: 'Music',
      volunteer: 'Available',
      imageUrl: '/public/Slider/Epic_music_festival.webp',
      attendees: ['user1', 'user2'],
      maxAttendees: 1000,
      createdBy: 'event_organizer_1'
    },
    {
      id: '2',
      title: 'Tech Innovation Summit',
      description: 'Discover the latest innovations in technology and network with industry leaders.',
      date: '2025-08-20T09:00:00Z',
      location: 'Convention Center',
      price: 149.99,
      district: 'Downtown',
      type: 'Technology',
      volunteer: 'Required',
      imageUrl: '/public/Slider/Tech_summit.webp',
      attendees: ['user3'],
      maxAttendees: 500,
      createdBy: 'event_organizer_2'
    },
    {
      id: '3',
      title: 'Gourmet Food & Wine Festival',
      description: 'Taste exquisite cuisines from world-class chefs and sample premium wines.',
      date: '2025-09-10T12:00:00Z',
      location: 'Downtown District',
      price: 75.50,
      district: 'Downtown',
      type: 'Food & Drink',
      volunteer: 'Available',
      imageUrl: '/public/Slider/food_and_wine.webp',
      attendees: [],
      maxAttendees: 300,
      createdBy: 'event_organizer_3'
    },
    {
      id: '4',
      title: 'Startup Networking Event',
      description: 'Connect with entrepreneurs and investors in this exclusive networking event.',
      date: '2025-07-25T17:30:00Z',
      location: 'Business Hub',
      price: 25.00,
      district: 'Uptown',
      type: 'Business',
      volunteer: 'Not Available',
      imageUrl: '/public/Slider/Epic_music_festival.webp',
      attendees: ['user1'],
      maxAttendees: 150,
      createdBy: 'event_organizer_4'
    },
    {
      id: '5',
      title: 'Art Gallery Exhibition',
      description: 'Explore contemporary art from emerging and established artists.',
      date: '2025-08-05T14:00:00Z',
      location: 'Modern Art Gallery',
      price: 15.00,
      district: 'Arts District',
      type: 'Art & Culture',
      volunteer: 'Available',
      imageUrl: '/public/Slider/Tech_summit.webp',
      attendees: ['user2', 'user3'],
      maxAttendees: 200,
      createdBy: 'event_organizer_5'
    },
    {
      id: '6',
      title: 'Fitness Bootcamp Challenge',
      description: 'Push your limits in this intensive outdoor fitness challenge.',
      date: '2025-07-30T06:00:00Z',
      location: 'City Park',
      price: 35.00,
      district: 'Parkside',
      type: 'Sports & Fitness',
      volunteer: 'Required',
      imageUrl: '/public/Slider/food_and_wine.webp',
      attendees: [],
      maxAttendees: 50,
      createdBy: 'event_organizer_6'
    },
    {
      id: '7',
      title: 'Community Cleanup Day',
      description: 'Join us for a free community service event to clean up our local parks.',
      date: '2025-08-15T08:00:00Z',
      location: 'Riverside Park',
      price: 0,
      district: 'Riverside',
      type: 'Community Service',
      volunteer: 'Required',
      imageUrl: '/public/Slider/Epic_music_festival.webp',
      attendees: ['user1', 'user4'],
      maxAttendees: 100,
      createdBy: 'community_organizer'
    },
    {
      id: '8',
      title: 'Luxury Gala Dinner',
      description: 'An exclusive black-tie gala dinner with celebrity guests and entertainment.',
      date: '2025-09-22T19:00:00Z',
      location: 'Grand Ballroom',
      price: 299.99,
      district: 'Downtown',
      type: 'Formal Event',
      volunteer: 'Not Available',
      imageUrl: '/public/Slider/Tech_summit.webp',
      attendees: [],
      maxAttendees: 75,
      createdBy: 'luxury_events'
    }
  ];

  export default mockEvents;